/**
 * Read-only portfolio snapshot service.
 *
 * Resolves a Telegram identity, reads wallet balances and successful activity
 * concurrently, and returns deterministic decimal-string data for rendering.
 *
 * @module portfolioSnapshotService
 */

import {
  aggregateDepositActivity,
  type DepositActivityTotal,
} from '../../queries/deposit.query';
import {
  aggregateSwapActivity,
  type SwapActivityTotal,
} from '../../queries/swap.query';
import { getUserIdentityByTelegramId } from '../../queries/user.query';
import {
  findPortfolioWallets,
  type PortfolioWalletRecord,
} from '../../queries/wallet.query';
import {
  portfolioMetrics,
  type PortfolioMetricsRecorder,
} from './metrics';
import { addStoredDecimals, standardDecimal } from '../../utils/decimal';

/** One supported wallet's exact decimal balance fields in a portfolio snapshot. */
export interface PortfolioBalance {
  /** Uppercase supported currency code. */
  currency: string;
  /** Available wallet balance preserving stored precision. */
  available: string;
  /** Locked wallet balance preserving stored precision. */
  locked: string;
  /** Exact available-plus-locked total. */
  total: string;
  /** Wallet update timestamp in ISO format. */
  updatedAt: string;
}

/** Read-only portfolio balances and aggregate activity as of one timestamp. */
export interface PortfolioSnapshot {
  /** ISO timestamp generated by the service clock. */
  asOf: string;
  /** Deterministically ordered supported-wallet balances. */
  balances: PortfolioBalance[];
  /** Aggregate successful deposit and swap activity. */
  activity: {
    deposits: DepositActivityTotal[];
    swaps: SwapActivityTotal[];
  };
}

/** Reader contract that keeps identity lookup separate from three concurrent reads. */
export interface PortfolioSnapshotReader {
  /**
   * Resolves the local user identity without exposing private user fields.
   *
   * @param telegramId - Telegram identity to resolve.
   * @returns Local user id, or null when no identity exists.
   */
  resolveUserId(telegramId: string): Promise<{ id: string } | null>;
  /**
   * Reads supported and unsupported wallet records for later filtering.
   *
   * @param userId - Local user identifier.
   * @returns Wallet rows with exact stored balances and timestamps.
   */
  readWallets(userId: string): Promise<PortfolioWalletRecord[]>;
  /**
   * Reads aggregate successful deposit activity.
   *
   * @param userId - Local user identifier.
   * @returns Aggregate deposit totals.
   */
  readDeposits(userId: string): Promise<DepositActivityTotal[]>;
  /**
   * Reads aggregate successful swap activity.
   *
   * @param userId - Local user identifier.
   * @returns Aggregate swap totals.
   */
  readSwaps(userId: string): Promise<SwapActivityTotal[]>;
}

const defaultReader: PortfolioSnapshotReader = {
  resolveUserId: getUserIdentityByTelegramId,
  /** Reads enabled catalog wallets for the resolved user in code order. */
  readWallets: findPortfolioWallets,
  /** Reads aggregate successful deposits for the resolved user. */
  readDeposits: (userId) =>
    aggregateDepositActivity({ userId, status: 'success' }),
  /** Reads aggregate successful swaps for the resolved user. */
  readSwaps: (userId) =>
    aggregateSwapActivity({ userId, status: 'success' }),
};

/** Keeps injected portfolio readers deterministic in the same order as the SQL query. */
const sortPortfolioWallets = (
  left: PortfolioWalletRecord,
  right: PortfolioWalletRecord,
): number => left.currency.toLowerCase().localeCompare(right.currency.toLowerCase());

/**
 * Maps one supported wallet to its privacy-safe exact-decimal portfolio balance.
 *
 * @param wallet - Wallet row selected for the portfolio.
 * @returns Uppercase currency and available, locked, total, and ISO timestamp fields.
 */
const mapWalletToPortfolioBalance = (wallet: PortfolioWalletRecord): PortfolioBalance => ({
  currency: wallet.currency.toUpperCase(),
  available: standardDecimal(wallet.balance),
  locked: standardDecimal(wallet.lockedBalance),
  total: addStoredDecimals(wallet.balance, wallet.lockedBalance),
  updatedAt: wallet.updatedAt.toISOString(),
});

export interface PortfolioSnapshotDependencies {
  reader?: PortfolioSnapshotReader;
  metrics?: PortfolioMetricsRecorder;
  clock?: () => Date;
}

/** Creates the read-only portfolio snapshot workflow with injectable dependencies. */
export const createPortfolioSnapshotService = ({
  reader = defaultReader,
  metrics = portfolioMetrics,
  clock = () => new Date(),
}: PortfolioSnapshotDependencies = {}) => ({
  getSnapshot: async (telegramId: string): Promise<PortfolioSnapshot | null> => {
    const startedAt = Date.now();
    let outcome: 'success' | 'empty' | 'error' = 'error';
    try {
      const identity = await reader.resolveUserId(telegramId);
      if (!identity) return null;

      const [wallets, deposits, swaps] = await Promise.all([
        reader.readWallets(identity.id),
        reader.readDeposits(identity.id),
        reader.readSwaps(identity.id),
      ]);
      const balances = [...wallets]
        .sort(sortPortfolioWallets)
        .map(mapWalletToPortfolioBalance);
      outcome = balances.length === 0 ? 'empty' : 'success';
      return {
        asOf: clock().toISOString(),
        balances,
        activity: { deposits, swaps },
      };
    } finally {
      metrics.record(outcome, Date.now() - startedAt);
    }
  },
});

export type PortfolioSnapshotService = ReturnType<typeof createPortfolioSnapshotService>;

/** Shared read-only portfolio snapshot service. */
export const portfolioSnapshotService = createPortfolioSnapshotService();
