/**
 * Safe error formatting for the administrator-creation CLI.
 *
 * @module adminCliErrors
 */

interface ErrorWithCause {
  code?: string;
  message?: string;
  cause?: unknown;
}

const deepestDatabaseError = (error: unknown): ErrorWithCause => {
  let current = error as ErrorWithCause;
  const visited = new Set<unknown>();
  while (current?.cause && !visited.has(current.cause)) {
    visited.add(current);
    current = current.cause as ErrorWithCause;
  }
  return current ?? {};
};

/** Converts driver and Drizzle wrapper failures into safe, actionable CLI output. */
export const adminCreationErrorMessage = (error: unknown): string => {
  const databaseError = deepestDatabaseError(error);
  switch (databaseError.code) {
    case '23505':
      return 'An admin with that email already exists';
    case '42P01':
      return 'The admin tables do not exist. Run `cd apps/api && bun run db:migrate`, then retry';
    case 'ECONNREFUSED':
      return 'PostgreSQL is not accepting connections. Start PostgreSQL and verify DATABASE_URL, then retry';
    case '28P01':
      return 'PostgreSQL rejected the configured credentials. Check DATABASE_URL, then retry';
    case '3D000':
      return 'The configured PostgreSQL database does not exist. Create it or update DATABASE_URL, then retry';
    default:
      // Do not print the outer Drizzle message because it contains SQL parameters,
      // including the password hash generated by this command.
      return databaseError.message && databaseError !== error
        ? `Unable to create admin: ${databaseError.message}`
        : 'Unable to create admin. Check PostgreSQL and the latest migration, then retry';
  }
};
